GET http://localhost:5000/api/qlnv/lines    

###
POST http://localhost:5000/api/qlnv/lines
Content-Type: application/json

{
    "lineNumber": 15,
    "description": "line 15",
    "status": true
}


###
PUT http://localhost:5000/api/qlnv/lines
Content-Type: application/json

{
    "id":"6219be2c770fd22f14521c70",
    "lineNumber": 15,
    "description": "Tuyến 15",
    "status": true
}


###
DELETE  http://localhost:5000/api/qlnv/lines/lineNumber=12